on: 
  push:
    branches:
      - main
    paths: 
      - app/main.cpp
      - test/test.sh
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: test
      run: test/test.sh 
